### ISSUE TITLE
Invalid Version when Using Self-Compiled/Beta PyTorch

### ISSUE THREAD

**Issue by billzhonggz** [ad12/meddlr#59]
I encountered an exception when running `import meddlr.ops as oF` in an NGC PyTorch container.

The exception says,

```python
>>> import meddlr.ops as oF
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/meddlr/meddlr/__init__.py", line 3, in <module>
    from meddlr.engine.model_zoo import get_model_from_zoo
  File "/workspace/meddlr/meddlr/engine/__init__.py", line 10, in <module>
    from .hooks import *  # noqa
  File "/workspace/meddlr/meddlr/engine/hooks.py", line 19, in <module>
    from meddlr.evaluation.testing import flatten_results_dict
  File "/workspace/meddlr/meddlr/evaluation/__init__.py", line 2, in <module>
    from .recon_evaluation import ReconEvaluator  # noqa: F401
  File "/workspace/meddlr/meddlr/evaluation/recon_evaluation.py", line 16, in <module>
    from meddlr.data.transforms.transform import build_normalizer
  File "/workspace/meddlr/meddlr/data/__init__.py", line 1, in <module>
    from meddlr.data import build, catalog, collate, data_utils, slice_dataset
  File "/workspace/meddlr/meddlr/data/build.py", line 13, in <module>
    from meddlr.data.slice_dataset import SliceData
  File "/workspace/meddlr/meddlr/data/slice_dataset.py", line 10, in <module>
    from meddlr.data.transforms.transform import DataTransform
  File "/workspace/meddlr/meddlr/data/transforms/transform.py", line 9, in <module>
    from meddlr.forward import SenseModel
  File "/workspace/meddlr/meddlr/forward/__init__.py", line 1, in <module>
    from meddlr.forward import mri
  File "/workspace/meddlr/meddlr/forward/mri.py", line 4, in <module>
    import meddlr.ops as oF
  File "/workspace/meddlr/meddlr/ops/__init__.py", line 1, in <module>
    from meddlr.ops import categorical, complex, fft, utils  # noqa: F401
  File "/workspace/meddlr/meddlr/ops/fft.py", line 10, in <module>
    if env.pt_version() >= [1, 6]:
  File "/workspace/meddlr/meddlr/utils/env.py", line 314, in pt_version
    version = [dtype(x) for x in version]
  File "/workspace/meddlr/meddlr/utils/env.py", line 314, in <listcomp>
    version = [dtype(x) for x in version]
ValueError: invalid literal for int() with base 10: '0a0'
```

I checked the related lines, the code assumes the PyTorch is using stable versions and installed from binary packs.

https://github.com/ad12/meddlr/blob/b2f055b482c534a2a6eb161c19e6abb6ea94c196/meddlr/utils/env.py#L314

However, the PyTorch in the NGC container is self-complied, and the version string contains a commit ID. It looks like this,

```python
>>> import torch
>>> torch.__version__
'1.13.0a0+08820cb'
```

I suspect that's why it triggered the exception.

Would you please kindly modify the function to accept the version strings like this?

**Comment by ad12** [comment]
Thanks for raising this bug! #61 fixes this - meddlr v0.0.4 has this most recent push
